
services:
  vector_db:
    image: qdrant/qdrant
    container_name: vector_db
    ports:
      - "6333:6333"
    volumes:
      - ./vector_db:/qdrant/storage
    restart: always

  ingestion_service:
    # build: ./ingestion_service
    build:
      context: .
      dockerfile: ingestion_service/Dockerfile
    image: ghcr.io/schultzvv/ingestion_service:latest
    container_name: ingestion_service
    ports:
      - "5003:5003"
    depends_on:
      - vector_db
    volumes:
      - ./ingestion_service:/app
      - ./shared:/app/shared
    restart: always
    environment:
      - DEBUG=True

  retrieval_service:
    build:
      context: .
      dockerfile: retrieval_service/Dockerfile
      args:
        HUGGINGFACE_TOKEN: ${HUGGINGFACE_TOKEN}
    image: ghcr.io/schultzvv/retrieval_service:latest
    container_name: retrieval_service
    ports:
      - "5004:5004"
    depends_on:
      - vector_db
    volumes:
      - ./retrieval_service:/app
      - ./shared:/app/shared
    restart: always
    env_file:
      - .env
    environment:
      - DEBUG=True
