version: "3.8"

services:
  vector_db:
    image: qdrant/qdrant
    container_name: vector_db
    ports:
      - "6333:6333"
    volumes:
      - ./vector_db:/qdrant/storage
    restart: always

  ingestion_service:
    image: ghcr.io/schultzvv/ingestion_service:latest
    container_name: ingestion_service
    ports:
      - "5003:5003"
    depends_on:
      - vector_db
    restart: always
    environment:
      - DEBUG=False

  retrieval_service:
    image: ghcr.io/schultzvv/retrieval_service:latest
    container_name: retrieval_service
    ports:
      - "5004:5004"
    depends_on:
      - vector_db
    restart: always
    environment:
      - DEBUG=False
    env_file:
      - .env
