version: "3.8"

services:
  vector_db:
    image: qdrant/qdrant
    container_name: vector_db
    ports:
      - "6333:6333"
    volumes:
      - ./vector_db:/qdrant/storage
    restart: always

  ingestion_service:
    build: ./ingestion_service
    container_name: ingestion_service
    ports:
      - "5003:5003"
    depends_on:
      - vector_db
    volumes:
      - ./ingestion_service:/app
    restart: always

  retrieval_service:
    build:
      context: ./retrieval_service
      args:
        HUGGINGFACE_TOKEN: ${HUGGINGFACE_TOKEN}
    container_name: retrieval_service
    ports:
      - "5004:5004"
    depends_on:
      - vector_db
    volumes:
      - ./retrieval_service:/app
    restart: always
    env_file:
      - .env
