name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Login no GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin

      - name: Build ingestion_service
        run: |
          docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/hsmart-ingestion_service:latest \
            -f ingestion_service/Dockerfile .

      - name: Build retrieval_service
        run: |
          docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/hsmart-retrieval_service:latest \
            -f retrieval_service/Dockerfile .

      - name: Push ingestion_service image
        run: docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/hsmart-ingestion_service:latest

      - name: Push retrieval_service image
        run: docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/hsmart-retrieval_service:latest
